### ISSUE TITLE
Delete spaces after/before key name in module/instance properties

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides#1]
if a set a module property with following value : {{ prop_instance}}/{{prop_instance}}, It adds 2 instance properties (one with a space before key name, one without)
--> Hesperides should not create 2 different properties

Other case : using a global property at module level with a space should work

LINK TO [hesperides-gui#1](https://github.com/voyages-sncf-technologies/hesperides-gui/issues/1)

**Comment by stidiovip** [comment]
This has also impact on default values

**Comment by stidiovip** [comment]
Several tests are required for already existing values !

**Comment by stidiovip** [comment]
Fixed on release 2.0.0
