### ISSUE TITLE
Remove item from store with TTL

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#10]
Actually, when you delete module, techno or platform, data not really remove in database.
Remove just add delete event and remove item in ELK entry.

The goal is keep same behavior but add TTL on item.
TTL must be high (6month ? 1 year).

When TTL is outdated, idem will be remove.

**Warning**
Redis or MondoDB support TTL but not some other database.

**Comment by Lucas-C** [comment]
Elasticsearch n'est plus un composant de l'archi v4
