### ISSUE TITLE
hide passwords in global properties too

### ISSUE THREAD

**Issue by JPRaw** [voyages-sncf-technologies/hesperides#12]
Hello,

Context : on a given platform, 4 modules (out of 5) use the same couple of login/password.
So, using a global property seems to be the easiest way to propagate the password.

Problem : if I use a global property within a property that uses the @password pattern, then the value of this global property is still displayed.

A solution could be to directly use a pattern @password on a global prop ?

Thanks
Jean-Philippe

**Comment by bubulemaster** [comment]
Hi,

sorry, but, Hesperides cannot support annotation in globals properties.

Hesperidse store template and Hesperides store value of properties (platform).

How Hesperides make link between model and properties' value ?

When Hesperides want generate file for example, Hesperides take template, generate a model (that mean generate list of properties declarated in template, with attributes [required, password...]).

After, Hesperides take platform (list of stored properties and value).

Then Hesperides check properties item (required, pattern...) with value of properties.

Finish, replace in template properties.

This technical implementation make sens cause Hesperides concept separate template en valuation.

Global properties is just a name. All properties store in platform with path. 
Global properties is just properties stored with no path (remember path is logical representation in platform).

Sorry :-(
