### ISSUE TITLE
Ajouter le concept de "user" dans les events.

### ISSUE THREAD

**Issue by Sylvain-maillard** [voyages-sncf-technologies/hesperides#122]
Dans le legacy, chaque event est associé à un user. 
On n'a pas ce concept dans le reboot de l'application.
Il faut l'ajouter.

**Comment by thomaslhostis** [comment]
L'utilisateur est ajouté aux events dans le codec legacy. Ce que tu veux dire, c'est qu'on ajoute l'utilisateur aux events natifs Axon pour le futur stockage ?

**Comment by Sylvain-maillard** [comment]
Oui c'est ça :) en fait l'utilisateur est un concept important qu'on doit faire apparaître dans le domaine.

**Comment by thomaslhostis** [comment]
Ok pour moi. Tu vas faire ça en Kotlin ? 😄
