### ISSUE TITLE
Implémenter l'Indexation par replay des events présents dans l'eventstore

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#124]
Nous devons implémenter la réindexation, il s'agit de la première tâche réalisée par l'application au démarrage.
L'application doit prendre en charge les events connus dans la refonte et ne pas planter sur ceux non connus

**Comment by Sylvain-maillard** [comment]
la réindexation, c'est l'idée de rejouer tous les évents de la base legacy pour mettre à jour l'ELS c'est bien ça ?

**Comment by victorsalaun** [comment]
Oui c'est bien ça. Cette tâche n'est pas prioritaire mais faut y prêter attention lors de la cohabitation hespérides spring et legacy.
De plus l'indexation dans le legacy est buggée

**Comment by victorsalaun** [comment]
MAJ du framework Axon en 3.2 http://www.axonframework.org/news/axon-3-2-released/
**Permattant le reset / replay** 🤸‍♀️ 

> One major new feature is the addition of an API call to initiate a “reset” of a tracking event processors. This reset effectively causes a replay of the processor. Event Handling components can be notified of this reset by implementing an @ResetHandler annotated method. Furthermore, events that are delivered as part of a “replay” (i.e. events that had already been published at the time the processor was reset) can be ignored by a handler by annotating it with @AllowReplay(false), or alternatively by adding a parameter of type ReplayStatus.

**Comment by Sylvain-maillard** [comment]
ok du coup on inclut dans ce ticket la capacité de "remplir" les views à partir des anciens events via le replay.
