### ISSUE TITLE
Migrer vers Spring Boot 2

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#132]
La version 2 de Spring Boot est disponible.

https://spring.io/blog/2018/03/01/spring-boot-2-0-goes-ga

```
<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter -->
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter</artifactId>
    <version>2.0.0.RELEASE</version>
</dependency>
```

**Comment by thomaslhostis** [comment]
Je suis plutôt pour, à voir pour ce qui est des impacts, la compatibilité avec l'existant et les ressources disponibles.

**Comment by Sylvain-maillard** [comment]
ça peut être sympa pour rester up-to-date sur les frameworks. 
Sachant qu'on utilise pas le système "spring-webflux" pour l'instant

**Comment by victorsalaun** [comment]
Oui l'idée est d'être up-to-date afin de rendre l'application sexy et d'attirer des contributeurs.

**Comment by victorsalaun** [comment]
Penser à vérifier la compatibilité avec axon.
Actuellement axon 3.2 utilise la dépendance suivante pour fonctionner avec spring :
```
<dependency>
    <groupId>org.axonframework</groupId>
    <artifactId>axon-spring-boot-starter</artifactId>
    <version>3.2</version>
</dependency>
```
Cette dernière se base sur :
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starters</artifactId>
    <version>1.5.7.RELEASE</version>
    <relativePath />
</parent>
```

**Comment by Sylvain-maillard** [comment]
Yes! ya déjà une pr: https://github.com/AxonFramework/AxonFramework/pull/545 
à suivre donc.

**Comment by Lucas-C** [comment]
D'après les commentaires dans l'issue mentionnée par Sylvain, ce devrait être inclus dans la v3.4 qui a été releasée récemment.  A noter également qu'Axon est passée en v4.0 et devenu un framework.

Passer à SpringBoot 2 permettrait entre autres de bénéficier des collations pour MongoDB, _cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/359
