### ISSUE TITLE
Mettre en place la centralisation des logs

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#138]
Attention: ne pas versionner cette conf sous Github

**Comment by Lucas-C** [comment]
> Thomas: Si Actuator ne le fait pas, utiliser les intercepteurs Spring

**Comment by Lucas-C** [comment]
Cette tâche sera également l'occasion de vérifier qu'on est bien capable de loguer les erreurs de connexion LDAP

**Comment by Lucas-C** [comment]
Fait, je clôture
