### ISSUE TITLE
Déployer sur Heroku

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#139]
Permettrait d'avoir une version "démo publique"

Il en existait une historiquement : https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/docs/index.html#L43

**Comment by Lucas-C** [comment]
RAF:
- trouver comment mettre à jour une image Docker une fois qu'elle est publiée:

    The process type web was not updated, because it is already running the specified docker image.

- reduire usage RAM:

    2019-10-11T21:37:01.989328+00:00 heroku[web.1]: Process running mem=861M(168.3%)

**Comment by Lucas-C** [comment]
Done
