### ISSUE TITLE
Comment releaser l'appli ?

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#141]
Problématique : définir un process pour faire une release propre

**Comment by victorsalaun** [comment]
Release fonctionnel.
* Utilisation du plugin Gitflow dans un job Jenkins -> Création d'un tag de release etc...
* Stage Travis déployant les tags de release sur Nexus de Sonatype
* Stage Travis déployant des images docker sur la base du nom de la branche (donc aussi pour les tags)
