### ISSUE TITLE
Migrate to Java 10

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#149]
Is it possible? At what cost? If not why?

Low level priority

**Comment by victorsalaun** [comment]
Test rapide de faisabilité raté 😞 

La compile du premier module "domain" plante :

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.LombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by Sylvain-maillard** [comment]
lombok ne serait pas compatible java 10 ? :)

**Comment by mareths** [comment]
Ça se retente apparemment ;)

https://github.com/rzwitserloot/lombok/issues/1644

**Comment by Lucas-C** [comment]
On pourrait se passer de lombok avec Java 10/11

**Comment by Lucas-C** [comment]
Je clôture : nous employons Java 11 : https://github.com/voyages-sncf-technologies/hesperides/blob/master/Dockerfile#L12

Et pour la partie Lombok, il existe https://github.com/voyages-sncf-technologies/hesperides/issues/847
