### ISSUE TITLE
The API returns an error without an explanatory message when a template with @ default = "" is uploaded

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#15]
Hello,

EDIT: bug reproduction with curl:
```
curl -kv -X PUT 'https://$HESPERIDES_HOST/rest/modules/nf-catalogBuilder/1.0-SNAPSHOT/workingcopy/templates' -H 'Authorization: Basic bHVjYXNfY2ltb246dnNjdC04ODg=' -H 'Content-Type: application/json; charset=UTF-8' --data-binary $'{\n  "name": "dummy.cfg",\n  "filename": "dummy.cfg",\n  "location": "/",\n  "content": "x={{x|@default \\"\\"}}",\n  "version_id": 1\n}'
```
There is already a generic error message that I had spoiled:
```
"message":"Annotation '@default' is not valid for property 'x'. Please check it !"
```
I take the point to do the dev and PR that goes well to add a detailed message of the type: {{InvalidTemplate: empty @default attribute not allowed}}.

Seen with Emeric on JIRA:
- dev to be done on : https://github.com/voyages-sncf-technologies/hesperides/blob/master/src/main/java/com/vsct/dt/hesperides/templating/models/Property.java#L82
- tests to be added
- review the other messages
Pattern : InvalidTemplate: empty @pattern attribute not allowed

**Comment by Lucas-C** [comment]
I won't have time to fix this before the end of the year, but I've made some progress and I'll definitively take the time to PR this soon.

Some code I've tested:
```
    private Property createPropertyFromFromString(String template) {
        MustacheFactory mustacheFactory = new DefaultMustacheFactory();
        DefaultMustache defaultMustache = (DefaultMustache)mustacheFactory.compile(new StringReader(template), template);
        return new Property(defaultMustache);
    }

    @Test
    public void shouldCreateModelFromCode() throws NoSuchFieldException, IllegalAccessException {
        Property prop = createPropertyFromFromString("{{x|@default \"default\" @pattern \"pattern\" @password @comment \"comment\"}}");
        assertThat("default").isEqualTo(prop.getDefaultValue());
        assertThat("pattern").isEqualTo(prop.getPattern());
        assertThat(prop.isPassword()).isTrue();
        assertThat("comment").isEqualTo(prop.getComment());
    }
```

**Comment by Lucas-C** [comment]
A comment btw: the README indicate "Do you have changes to contribute? Please see the Development page." but I don't see any such page.

Also, it may be handy to give some tips in the README on how to execute tests:
```
mvn -Dtest=HesperidesPropertiesModelTest#shouldCreateModelFromCode test
```

**Comment by Lucas-C** [comment]
Ready for review !
I added 5 tests.
I have to say that seeing code like this is a bit frightening / worrying :
https://github.com/voyages-sncf-technologies/hesperides/blob/master/src/main/java/com/vsct/dt/hesperides/templating/models/annotation/HesperidesAnnotationConstructor.java#L66

**Comment by Willymontaz** [comment]
It would be far easier and readable to use a switch statement on the string
since we only have 4 or 5 annotations

**Comment by Lucas-C** [comment]
Agreed.
I'm going to open another issue to clean up this

**Comment by bubulemaster** [comment]
Reflexion is use to allow extends.

Extrends not yet avaible cause we need do some change is model.

**Comment by Willymontaz** [comment]
Service Providers via JAR specification seems more suitable for that purpose

http://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Service_Provider

**Comment by stidiovip** [comment]
Fixed on release CHAOS_2.2.1 thanks to @Lucas-C ! See you for more contributions ;)
