### ISSUE TITLE
Nettoyer les données Redis

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#155]
Nettoyer les modules, plateformes et technos qui ont été supprimés

**Comment by victorsalaun** [comment]
Il s'agit de supprimer l'ensemble de events d'une entité dont le dernier event est une suppression.
A mettre en place sous la forme par exemple d'un batch pour les events de suppression datant de X jours (paramétrable)

-> Pas lié uniquement à redis mais à l'ensemble des implémentations d'eventstore

**Comment by Lucas-C** [comment]
Fait durant la migration
