### ISSUE TITLE
Sorting of the iterable properties

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides#19]
1. It would be nice to have a sort button for iterable properties.
2. The order of display of the iterable props is not the same between 2 loading the props. Not practical if I want to visually compare my iterable props on 2 different tabs on my chrome.

A deterministic display order will be better.

**Comment by stidiovip** [comment]
Fixed on [PR 80](https://github.com/voyages-sncf-technologies/hesperides-gui/pull/80)

**Comment by mareths** [comment]
FIxed on CHAOS_2.2.2
