### ISSUE TITLE
Missing javadoc jar and source jar

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#197]
Le build travis ne passe plus depuis la release 0.0.1 car le deploiement vers nexus de sonatype est refusé  car nous ne générons pas la javadoc ni les sources :

> [ERROR] Rule failure while trying to close staging repository with ID "org[secure]-1000".
[ERROR] 
[ERROR] Nexus Staging Rules Failure Report
[ERROR] ==================================
[ERROR] 
[ERROR] Repository "org[secure]-1000" failures
[ERROR]   Rule "javadoc-staging" failures
[ERROR]     * Missing: no javadoc jar found in folder '/org/[secure]/infrastructure/0.0.1'
[ERROR]     * Missing: no javadoc jar found in folder '/org/[secure]/application/0.0.1'
[ERROR]     * Missing: no javadoc jar found in folder '/org/[secure]/domain/0.0.1'
[ERROR]     * Missing: no javadoc jar found in folder '/org/[secure]/presentation/0.0.1'
[ERROR]     * Missing: no javadoc jar found in folder '/org/[secure]/bootstrap/0.0.1'
[ERROR]   Rule "sources-staging" failures
[ERROR]     * Missing: no sources jar found in folder '/org/[secure]/infrastructure/0.0.1'
[ERROR]     * Missing: no sources jar found in folder '/org/[secure]/application/0.0.1'
[ERROR]     * Missing: no sources jar found in folder '/org/[secure]/domain/0.0.1'
[ERROR]     * Missing: no sources jar found in folder '/org/[secure]/presentation/0.0.1'
[ERROR]     * Missing: no sources jar found in folder '/org/[secure]/bootstrap/0.0.1'
[ERROR] 
[ERROR] 
[ERROR] Cleaning up local stage directory after a Rule failure during close of staging repositories: [org[secure]-1000]
[ERROR]  * Deleting context 3487914a7e00f8.properties
[ERROR] Cleaning up remote stage repositories after a Rule failure during close of staging repositories: [org[secure]-1000]
[ERROR]  * Dropping failed staging repository with ID "org[secure]-1000" (Rule failure during close of staging repositories: [org[secure]-1000]).

https://travis-ci.org/voyages-sncf-technologies/hesperides/jobs/380726666

**Comment by thomaslhostis** [comment]
@victorsalaun C'est toujours d'actualité ?

**Comment by victorsalaun** [comment]
ce n'est plus d'actualité, ça marche chez moi :trollface:
