### ISSUE TITLE
Filtering iterable properties

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides#20]
The filter of the iterable props operates only on the values ​​not on the property name.

Now, the values ​​can be long text, numbers, short at all and anything, so filter on the values ​​does not have too much interest in my sense. It will be better to be able to filter on the names of props as in the simple properties

**Comment by stidiovip** [comment]
Fixed on [PR-82](https://github.com/voyages-sncf-technologies/hesperides-gui/pull/82)

**Comment by mareths** [comment]
Fixed on CHAOS_2.2.2
