### ISSUE TITLE
Accès en lecture aux API non sensibles de manière anonyme

### ISSUE THREAD

**Issue by jceloi** [voyages-sncf-technologies/hesperides#208]
**Problématique**
Actuellement, il est impossible d'accéder aux API d'Hesperides de manière anonyme. Cela implique qu'il n'est pas possible sans passer de header additionnel d'aller récupérer des templates valorisés. Hors certains outils ne permettent pas forcément de valoriser un header (ex. lecture de properties par Spring Boot "directe" via spring.config.additional-location ou archaius via archaius.configurationSource.additionalUrls )

**Solution souhaitée**
Idéalement, ouvrir certaines API non sensibles (plateformes non flaggées "PROD" par exemple) en anonyme sur les opérations de lectures uniquement.

**Contexte sup**
Cas d'usage : image docker se configurant automatiquement au démarrage en allant lire une configuration Hesperides.

**Comment by Lucas-C** [comment]
L'utilisateur n'a plus ce besoin. J'en viens d'en discuter avec lui, et son souhait était d'utiliser Hesperides avec du SpringBoot config / archaius en Java.

Pour clarifier, le besoin n'était pas tant "limité au horsprod" mais limité aux cas sans mots de passe sensibles.

Dans le même ordre d'idée, nous comptons étudier la compatibilité d'Hesperides avec https://github.com/kelseyhightower/confd
