### ISSUE TITLE
 Naming the sub-blocks of the iterable properties

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides#21]
It will be good if I can name my sub-block of iterable props so that I find myself easily without going to look at the block props.

@Nice to have: The name of the sub-block can for example appear in comment in my generated template file

**Comment by stidiovip** [comment]
Fixed on [PR-83](https://github.com/voyages-sncf-technologies/hesperides-gui/pull/83)

**Comment by mareths** [comment]
Fixed on CHAOS_2.2.2
