### ISSUE TITLE
POST /applications/{application_name}/platforms

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#231]
Crée la plateforme d'une application, potentiellement à partir d'une autre plateforme.

**Input**

Paramètres de requêtes facultatifs :
* from_application
* from_platform

Corps de la requête :

    {
      "application_name": "",
      "application_version": "",
      "platform_name": "",
      "production": false,
      "version_id": 0,
      "modules": [
        {
          "id": 0,
          "name": "",
          "version": "",
          "path": "",
          "working_copy": false,
          "properties_path": "",
          "instances": [
            {
              "name": "",
              "key_values": [
                {
                  "value": "",
                  "name": ""
                }
              ]
            }
          ]
        }
      ]
    }

**Output**

Code 200 + Structure identique à l'input :

    {
      "application_name": "",
      "application_version": "",
      "platform_name": "",
      "production": false,
      "version_id": 0,
      "modules": [
        {
          "id": 0,
          "name": "",
          "version": "",
          "path": "",
          "working_copy": false,
          "properties_path": "",
          "instances": [
            {
              "name": "",
              "key_values": [
                {
                  "value": "",
                  "name": ""
                }
              ]
            }
          ]
        }
      ]
    }

**Comment by thomaslhostis** [comment]
La création de base fonctionne. Il reste au moins à :
* Vérifier les droits
* Gérer la copie
* Vérifier d'autres règles de gestion ?

**Comment by Auff** [comment]
La refonte permet actuellement de créer une plateforme avec un module qui n'existe pas, une vérification est à faire !

**Comment by Lucas-C** [comment]
Fermé en faveur de https://github.com/voyages-sncf-technologies/hesperides/issues/362
