### ISSUE TITLE
PUT /applications/{application_name}/platforms

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#232]
Met à jour la plateforme d'une application, potentiellement à partir d'une autre plateforme.

**Input**

Paramètre de requête facultatif : copyPropertiesForUpgradedModules

TODO : Expliquer à quoi sert ce paramètre

Structure du body identique à celle de la création :

    {
      "application_name": "",
      "application_version": "",
      "platform_name": "",
      "production": false,
      "version_id": 0,
      "modules": [
        {
          "id": 0,
          "name": "",
          "version": "",
          "path": "",
          "working_copy": false,
          "properties_path": "",
          "instances": [
            {
              "name": "",
              "key_values": [
                {
                  "value": "",
                  "name": ""
                }
              ]
            }
          ]
        }
      ]
    }

**Output**

Code 200 + Structure identique à l'input :

    {
      "application_name": "",
      "application_version": "",
      "platform_name": "",
      "production": false,
      "version_id": 0,
      "modules": [
        {
          "id": 0,
          "name": "",
          "version": "",
          "path": "",
          "working_copy": false,
          "properties_path": "",
          "instances": [
            {
              "name": "",
              "key_values": [
                {
                  "value": "",
                  "name": ""
                }
              ]
            }
          ]
        }
      ]
    }

**Comment by baaroth** [comment]
PR#269 handles this WITHOUT any property copy

**Comment by Auff** [comment]
La refonte permet actuellement de mettre à jour une plateforme avec un module qui n'existe pas, une vérification est à faire.

**Comment by Lucas-C** [comment]
Fermé en faveur de https://github.com/voyages-sncf-technologies/hesperides/issues/362
