### ISSUE TITLE
[Legacy] Inconsistance sur le champ "comment" d'un Modèle

### ISSUE THREAD

**Issue by Auff** [voyages-sncf-technologies/hesperides#250]
Lors de la récupération du modèle d'un Module ou d'une techno, le champ comment, lorsqu'il n'est pas renseigné, peut avoir la valeur "" ou null
[Exemple ](https://hesperides/rest/templates/packages/miConfiguration.json/1.1.0/workingcopy/model)

name | "application_name"  | "mi.europe.call.frequency.ms"
-- | -- | --
comment | "" | null
required | false | false
defaultValue | "" | "300"
pattern | "" | ""
password | false | false

**Comment by Lucas-C** [comment]
Je clôture : ne s'applique plus en v4
