### ISSUE TITLE
[Refonte][Propriété] Annotation sans @ est un "comment"

### ISSUE THREAD

**Issue by Auff** [voyages-sncf-technologies/hesperides#256]
C'est un comportement du Legacy à reproduire.
Il doit être possible d'annoter une propriété avec un commentaire ("comment"), et ce sans préciser l'annotation @comment après le pipe ( | ).
De cette façon, un commentaire peut être composé d'espace.
Il est cependant nécessaire que cette annotation sans @ soit la première, sinon elle n'est pas reconnue.
exemple : {{solr.instance|instance du solr} 

Key | Value Legacy | Value Refonte
-- | -- | --
name | solr.host | solr.host
comment | hote du solr | ""
required | false | false
defaultValue | ""  | ""
pattern | ""  | ""
password | false | false

[template demo](https://hesperides/rest/templates/packages/demo/1.0/workingcopy/model)

**Comment by victorsalaun** [comment]
bien vu 👀

**Comment by Auff** [comment]
Une propriété de template ne pouvant avoir plusieurs fois la même Annotation, un "comment" sans @ ne peut exister en même temps qu'un "comment" commençant par "@comment"
