### ISSUE TITLE
[Refonte] Un seul exemplaire d'annotation par proriété

### ISSUE THREAD

**Issue by Auff** [voyages-sncf-technologies/hesperides#258]
Une exception ModelAnnotationException doit être levée si une propriété possède une annotation en plus d'un exemplaire. 
(cela comprends l'annotation "comment", qui peut être définit avec "@comment" ou si elle est définie juste après le pipe sans cette annotation)

**Comment by thomaslhostis** [comment]
Implémenté et testé unitairement
