### ISSUE TITLE
[Refonte] Les valeurs des annotations peuvent comprendre des @

### ISSUE THREAD

**Issue by Auff** [voyages-sncf-technologies/hesperides#259]
Bug crée par l'implémentation de la fonctionnalité d'annotation sur les propriétés.
La solution choisie de "spliter" par "@" n'est pas la bonne, ou du moins pas suffisamment développée.
Classe responsable : 
\domain\src\main\java\org\hesperides\domain\templatecontainers\entities\Property.java

name | varMailWithoutQuote | varMail
-- | -- | -- 
comment | null | numm
required | false | false
defaultValue | bob@bob.com | bob@bob.com
pattern |  "" | ""
password | false | false

[plus de détails ici](https://hesperides/#/techno/demo/1.0?type=workingcopy)

**Comment by thomaslhostis** [comment]
Implémenté et testé unitairement
