### ISSUE TITLE
Convert all source files line endings to LF

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#30]
Hi.

Would you agree on a commit / PR that convert all source files CRLFs to LFs ?
It is usually a good practice to stick with single-character line endings,
and such conversion can be done in a few very simple steps:
http://stackoverflow.com/a/1889699

**Comment by nboury-vsct** [comment]
+1 !

**Comment by JordanKergoat** [comment]
Hello, I agree, it make no sense to have different line endings character.

**Comment by Lucas-C** [comment]
Si c'est OK, je ferai la même chose sur hesperides-gui

**Comment by Lucas-C** [comment]
Is this good to go ?

**Comment by JordanKergoat** [comment]
Go to apply this on the Hesperides-gui part as well

**Comment by Lucas-C** [comment]
Done
