### ISSUE TITLE
Hesperides is now on Maven Central

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#301]
La release `0.1.3` d'Hespérides est sur le Maven Central 🎆 🎆 

https://search.maven.org/search?q=hesperides
https://mvnrepository.com/search?q=hesperides

Et apparaît bien sur aussi sur le Nexus de Sonatype https://oss.sonatype.org/#nexus-search;quick~hesperides

Pour rappel le ticket Jira de Sonatype : https://issues.sonatype.org/browse/OSSRH-38438

A confirmer si le déploiement se déroule bien à la prochaine release.

**Comment by Auff** [comment]
Ahah, nice, je n'avais pas vérifié jusque là, je m'étais arrêté au deuxième lien du ticket : 
Deploy release artifacts into the staging repository [https://oss.sonatype.org/service/local/staging/deploy/maven2](https://oss.sonatype.org/service/local/staging/deploy/maven2)

Mais c'est la fête :)

**Comment by victorsalaun** [comment]
Tu peux maintenant utiliser que des version releasées sur hesperides-data-migration
