### ISSUE TITLE
Historique des valeurs d'une propriété valorisée

### ISSUE THREAD

**Issue by Auff** [voyages-sncf-technologies/hesperides#302]
Il serait intéressant de pouvoir générer/consulter les différentes valorisations qu'une propriété a pu avoir.

**Comment by thomaslhostis** [comment]
Lié à https://github.com/voyages-sncf-technologies/hesperides/issues/826

**Comment by thomaslhostis** [comment]
Implémenté par https://github.com/voyages-sncf-technologies/hesperides/issues/826
