### ISSUE TITLE
teeproxy: Diff de droits sur les modules + propriétés itérables

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#305]
Objectif de l'issue : ignorer ces cas dans le diff des tests de NR comparés

---

Lorsqu'un module du legacy ne contient pas de droits (rights absent), l'appel au model du legacy renvoie rights: null alors que la nouvelle appli renvoie rights: {user: {read: null, write: null, execute: null}, ...

---

http://deadbabyboy:50080/rest/modules/app-event/5.2.6/workingcopy/model
http://localhost:8080/rest/modules/app-event/5.2.6/workingcopy/model

iterable_properties[name=healthChecks].fields[]: Expected 6 values but got 5

https://hesperides-dev:56789/#/techno/mesosapp/1.1?type=workingcopy

---

\+ _cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/337

\+ _cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/338

\+ _cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/339

\+ _cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/340

\+ _cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/341

**Comment by Lucas-C** [comment]
Migration terminée, je clôs cette _issue_
