### ISSUE TITLE
Diff de propriétés itérables

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#306]
http://deadbabyboy:50080/rest/modules/app-event/5.2.6/workingcopy/model
http://localhost:8080/rest/modules/app-event/5.2.6/workingcopy/model

iterable_properties[name=healthChecks].fields[]: Expected 6 values but got 5

https://hesperides-dev:56789/#/techno/mesosapp/1.1?type=workingcopy

**Comment by Lucas-C** [comment]
Fusionné dans https://github.com/voyages-sncf-technologies/hesperides/issues/305
