### ISSUE TITLE
Rendre compatible Hespérides avec Terraform (opérations CRUD sur chaque ressource)

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#308]
Un provider Terraform doit répondre aux opérations CRUD sur chaque ressource qu'il expose.

Afin de créer un [custom provider](https://www.terraform.io/docs/extend/writing-custom-providers.html) pour Hespérides, l'API d'Hespérides doit fournir les opérations CRUD sur chaque ressource.

**Comment by victorsalaun** [comment]
Help doc: https://www.hashicorp.com/blog/help-for-terraform-provider-developers

**Comment by Lucas-C** [comment]
@victorsalaun Peut-on clôre ce ticket comme tu as créé https://github.com/voyages-sncf-technologies/terraform-provider-hesperides ? :)

**Comment by victorsalaun** [comment]
Aucune objection à clôturer ce ticket. 👍

**Comment by Lucas-C** [comment]
Merci ;)
