### ISSUE TITLE
Use a switch instead of reflection in templating.models.annotation.HesperidesAnnotationConstructor:

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#32]
Spotted in #15

Relevant code: https://github.com/voyages-sncf-technologies/hesperides/blob/master/src/main/java/com/vsct/dt/hesperides/templating/models/annotation/HesperidesAnnotationConstructor.java#L47

**Comment by bubulemaster** [comment]
Reflexion is use to allow extends.

Extrends not yet avaible cause we need do some change is model.

**Comment by Willymontaz** [comment]
Service Providers via JAR specification seems more suitable for that purpose

http://docs.oracle.com/javase/7/docs/technotes/guides/jar/
jar.html#Service_Provider
