### ISSUE TITLE
Les rôles des utilisateurs sont stockés dans les évènements

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#332]
Le batch de migration des données doit inventer ces rôles pour balancer les évènements sur le bus, alors qu'on n'a pas besoin de stocker cette information.

**Comment by Lucas-C** [comment]
Objectif : faire en sorte que les événements dans la nouvelle version d'Hesperides ne contiennent pas cette information

**Comment by thomaslhostis** [comment]
Corrigé avec https://github.com/voyages-sncf-technologies/hesperides/pull/411
