### ISSUE TITLE
GET /events/{{stream_name}}

### ISSUE THREAD

**Issue by Auff** [voyages-sncf-technologies/hesperides#335]
Cet endpoint renvoie un tableau d'objets, correspondant aux events bruts, stockés dans l'Event Store.

Particularité de cet endpoint : 
* Impacte technos, module et plateforme
* Nécessite de contacter directement l'event store, et non la base d'état final, comme (presque) toutes les autres query
* Les Events stockés dans la refonte, ont légèrement changé de structure
* Le front se sert de cet endpoint, mais n'utilise réellement que le 
  * type (d'event)
  * timestamp
  * user
  * le comment (dans le cas d'un event concernant la valorisation d'une plateforme)

**Input**

Paramètres de requête : 
* path (obligatoire)
* page (recommandé)
* size (recommandé)

**Output**

Code 200 + Structure :
[
  {
    "type": "com.vsct.dt.hesperides.**eventLegacy**",
    "data": {},
    "timestamp": 1212121212121,
    "user": "bob_ross"
  }
]

**Comment by Lucas-C** [comment]
A prendre en compte également : https://github.com/voyages-sncf-technologies/hesperides/issues/55
