### ISSUE TITLE
Diff : propriété manquante

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#337]
*********************** Diff ***********************

http://deadbabyboy:50080/rest/modules/pao-bridge-jms/1.0.2-SNAPSHOT/workingcopy/model
http://localhost:8080/rest/modules/pao-bridge-jms/1.0.2-SNAPSHOT/workingcopy/model
https://hesperides-dev:56789/#/module/pao-bridge-jms/1.0.2-SNAPSHOT?type=workingcopy
key_value_properties[]: Expected 5 values but got 4

**Comment by Lucas-C** [comment]
Fusionné dans https://github.com/voyages-sncf-technologies/hesperides/issues/305
