### ISSUE TITLE
Diff dans la gestion de la valeur par défaut d'une propriété

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#338]
*********************** Diff ***********************

http://deadbabyboy:50080/rest/modules/lyriaweb-drupal/3.0.0/workingcopy/model
http://localhost:8080/rest/modules/lyriaweb-drupal/3.0.0/workingcopy/model
https://hesperides-dev:56789/#/module/lyriaweb-drupal/3.0.0?type=workingcopy
key_value_properties[name=drupal.wingit_baseurl].comment
Expected: null
     got: Wingit base url
 ; key_value_properties[name=drupal.wingit_baseurl].defaultValue
Expected: https://sandbox.thewingitapp.com/api| @comment 
     got: null

**Comment by Lucas-C** [comment]
Fusionné dans https://github.com/voyages-sncf-technologies/hesperides/issues/305
