### ISSUE TITLE
Propriété en trop

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#339]
*********************** Diff ***********************

http://deadbabyboy:50080/rest/modules/vsc-proposals-server-europe-war/129-SNAPSHOT/workingcopy/templates
http://localhost:8080/rest/modules/vsc-proposals-server-europe-war/129-SNAPSHOT/workingcopy/templates
https://hesperides-dev:56789/#/module/vsc-proposals-server-europe-war/129-SNAPSHOT?type=workingcopy
[]: Expected 10 values but got 11

**Comment by Lucas-C** [comment]
Fusionné dans https://github.com/voyages-sncf-technologies/hesperides/issues/305
