### ISSUE TITLE
Propriété itérable manquante

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#340]
*********************** Diff ***********************

http://deadbabyboy:50080/rest/modules/SncfFusionPlacesRef-nodejs/1.42.0/workingcopy/model
http://localhost:8080/rest/modules/SncfFusionPlacesRef-nodejs/1.42.0/workingcopy/model
https://hesperides-dev:56789/#/module/SncfFusionPlacesRef-nodejs/1.42.0?type=workingcopy
iterable_properties[]: Expected 2 values but got 1

**Comment by Lucas-C** [comment]
Fusionné dans https://github.com/voyages-sncf-technologies/hesperides/issues/305
