### ISSUE TITLE
Diff de version id et contenu

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#341]
*********************** Diff ***********************

http://deadbabyboy:50080/rest/modules/vad-mail/1.4-SNAPSHOT/workingcopy/templates/logback-files.properties
http://localhost:8080/rest/modules/vad-mail/1.4-SNAPSHOT/workingcopy/templates/logback-files.properties
https://hesperides-dev:56789/#/module/vad-mail/1.4-SNAPSHOT?type=workingcopy
content
Expected: auditoutlinefile.maxIndex=5
auditoutlinefile.maxFileSize=5MB
stackfile.maxIndex=5
stackfile.maxFileSize=5MB
xllogfile.maxIndex=5
xllogfile.maxFileSize=5MB
iologfile.maxIndex=5
iologfile.maxFileSize=5MB
     got: auditoutlinefile.maxIndex=5
auditoutlinefile.maxFileSize=5MB
stackfile.maxIndex=5
stackfile.maxFileSize=5MB
xllogfile.maxIndex=5
xllogfile.maxFileSize=5MB
iologfile.maxIndex=5
iologfile.maxFileSize=5MB

boobs
 ; version_id
Expected: 7
     got: 8

**Comment by victorsalaun** [comment]
What ? b**bs ???

**Comment by thomaslhostis** [comment]
T'as mis un filtre pour réagir aussi vite ? ^^

**Comment by victorsalaun** [comment]
tu sais comment attirer mon attention maintenant 😝

**Comment by Auff** [comment]
boobs check
Jeudi soir ?

**Comment by victorsalaun** [comment]
yes

**Comment by Auff** [comment]
Tu as mis 9 minutes à répondre, c'est pas très "Reactive", bien joué quand même 👯

**Comment by victorsalaun** [comment]
j'étais parti me prendre un ☕️  ‼️

**Comment by Auff** [comment]
Je passe la feature "Hesperides mobile" en prioritaire, histoire que tu ne puisses louper un boobs.  
Les boobs, c'est un peu ton "bat-signal".

**Comment by Lucas-C** [comment]
Fusionné dans https://github.com/voyages-sncf-technologies/hesperides/issues/305
