### ISSUE TITLE
Rework annotation system

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#35]
After issue #32 raise by @Lucas-C, I create this issue to explain more logic of annotation system.

Actually, annotation is attached to property like :
```
    private boolean password;
    private String comment;
    private final String name;
    private boolean required;
    private String defaultValue;
    private String pattern;
```

It's not good way cause, we cannot extends this.

To allow extends, we need refactor to(or something like) :
```
    private final String name;
    private Map<String, String> metadata
```

with this system, name of annotation is key and value is value.

Now, when annotation is found, we create an objet by loading class by name.
For example, `@defaut` load `HesperidesDefaultAnnotation` class.

This behaviours maybe need to rework like purpose @Willymontaz (Service Providers via JAR : http://docs.oracle.com/javase/7/docs/technotes/guides/jar/jar.html#Service_Provider)

/!\ Warning, this change have GUI impact.

**Comment by Lucas-C** [comment]
"Reworked" au cours de la refonte v4
