### ISSUE TITLE
Get Platform avec timestamp

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#356]
Cette fonctionnalité nécessite de comprendre le fonctionnement du replay avec Axon

Il faut qu'on soit capable de recréer en mémoire l'état d'une vue à un instant T en fonction d'un timestamp, pour implémenter le diff plateformes

Pour cela il faudra probablement qu'on contacte la communauté Axon (Google Group ?)

**Comment by Lucas-C** [comment]
_cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/219

**Comment by thomaslhostis** [comment]
Discussion Google Groups : https://groups.google.com/forum/#!topic/axonframework/Akh_1NFs7mU

**Comment by Lucas-C** [comment]
Durant l'implémentation de cette fonctionnalité, il ne faudra pas oublier de compléter un test dans `prod-perms.feature`

**Comment by Lucas-C** [comment]
Ressources impactées :
- `GET /applications/{application_name}/platforms/{platform_name}`
- `GET /applications/{application_name}/platforms/{platform_name}/properties`
