### ISSUE TITLE
Améliorer les messages d'erreurs

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#357]

**Comment by Lucas-C** [comment]
> Message d'erreur "404: There is no module XXX" alors que c'est le path qui n'existe pas

> Dans le cas de cette `MissingResourceException`, il serait préférable que le message d'erreur soit plus précis:
> - soit indiquer le chemin complet
> - soit indiquer que c'est directement le groupe logique qui n'existe pas (mieux)
