### ISSUE TITLE
Endpoint /file : fichier valorisé

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#361]
Objectif: implémenter la ressource `GET /applications/{application_name}/platforms/{platform_name}/{path}/{module_name}/{module_version}/instances/{instance_name}/{filename}` du legacy dans la nouvelle version:
https://github.com/voyages-sncf-technologies/hesperides/blob/fix/3.0.3/src/main/java/com/vsct/dt/hesperides/resources/HesperidesFilesResource.java#L163

L'ancien swagger est un bon point de départ.

Penser à inclure des tests BDDs couvrant les fonctionnalités de ce endpoint.
Voici 2 fichiers qui seront utiles pour cela :
- https://github.com/voyages-sncf-technologies/hesperides/blob/fix/3.0.3/src/test/java/com/vsct/dt/hesperides/files/FilesTest.java
- https://github.com/voyages-sncf-technologies/hesperides/blob/fix/3.0.3/src/test/java/com/vsct/dt/hesperides/resources/HesperidesFilesResourceTest.java

_cf._ also https://github.com/voyages-sncf-technologies/hesperides/issues/360 for this endpoint

**Comment by thomaslhostis** [comment]
L'idéal serait de compléter la glue "Then the files are successfully retrieved" (get-files.feature) par un appel à chaque fichier listé et vérifier simplement que le code retour est 200.

**Comment by Abdelmottaleb** [comment]
Ce service permet d’obtenir le contenu valorisé d’un Template donnée à partir de : 
 - d’une plateforme donnée
 - d’un module donné
 - d’une instance donnée

Les valeurs des propriétés du Template seront récupérées : 

 - à partir des propriétés valorisées de l’instance, Si le module déployé à la plateforme en question contient l’instance en question.
 - directement à partir des propriétés valorisées du module déployé, sinon
