### ISSUE TITLE
Gestion iso de la casse des caractères dans les identifiants

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#371]
Ex: noms de modules

_cf._ https://github.com/voyages-sncf-technologies/hesperides/issues/359#issuecomment-433458586 pour les choix qui s'offrent à nous. Je privilégierais bien la monté en Spring 2: https://github.com/voyages-sncf-technologies/hesperides/issues/132

J'ai débuté un commit sur cette branche : https://github.com/Lucas-C/hesperides/tree/case_insensitive_ids

**Comment by Lucas-C** [comment]
Il faudra compléter avec pas mal de tests BDDs: ce question affecte toutes les méthodes `/modules/...` de l'API

**Comment by Lucas-C** [comment]
From: https://stackoverflow.com/a/48840590/636849
> As at MongoDB 3.6, the default collation options can only be specified when a collection is created. There is no support for modifying the default collation options.

**Comment by Lucas-C** [comment]
Bon, même en-dehors de spring-data-mongodb, je n'arrive pas à faire fonctionner ces fichus Index avec le shell `mongo` :(

Étant donné un module `{ name: "ABC", version: "1.2.3", isWorkingCopy: true }`, je veux pouvoir le retrouver en cherchant sa variante _lowercase_:

    db.module.createIndex({key: 1}, {collation: {locale: "fr", strength: 2}})
    db.module.getIndexes()
    db.module.count({key: { name: "ABC", version: "1.2.3", isWorkingCopy: true }})
    db.module.count({key: { name: "abc", version: "1.2.3", isWorkingCopy: true }})

**Comment by thomaslhostis** [comment]
Je regarde ça dans la semaine

**Comment by Lucas-C** [comment]
OK. Je t'assigne le ticket alors.
J'ai MAJ la branche sur laquelle je travaille: https://github.com/Lucas-C/hesperides/tree/case_insensitive_ids
J'ai bien vérifié, j'utilisais bien une version de MongoDB qui support les collations pour mes tests.

**Comment by Lucas-C** [comment]
@brunoMod : Voici un exemple plus complet qui devrait fonctionner hors Hesperides, pour illustrer ce qu'on cherche à obtenir :
```
db.createCollection('module')
db.module.createIndex({key: 1}, {collation: {locale: "fr", strength: 2}})
db.module.insert({"key" : { "name" : "ABC", "version" : "1.2.3", "isWorkingCopy" : true }, "templates" : [ ], "technos" : [ ], "properties" : [ ], "versionId" : 1})
db.module.count({key: { name: "abc", version: "1.2.3", isWorkingCopy: true }})  // J'aimerais retrouver mon module et donc obtenir 1 au lieu de 0
```

**Comment by Lucas-C** [comment]
Aaaaah, ça marche en mettant la collation comme "valeur par défaut" au niveau de la collection !
```
db.createCollection('module', {collation: {locale: "fr", strength: 2}})
db.module.createIndex({key: 1})
db.module.insert({"key" : { "name" : "ABC", "version" : "1.2.3", "isWorkingCopy" : true }, "templates" : [ ], "technos" : [ ], "properties" : [ ], "versionId" : 1})
db.module.count({key: { name: "abc", version: "1.2.3", isWorkingCopy: true }})
```

**Comment by Lucas-C** [comment]
Il nous faudrait cette fonctionnalité : [DATAMONGO-1854: Add collation support for mongo repository interface](https://jira.spring.io/browse/DATAMONGO-1854)

**Comment by Lucas-C** [comment]
Voici comment vérifier, en appelant `ensureCaseInsensitivity(mongoTemplate, "module")` dans le constructeur de `MongoModuleProjectionRepository`, qu'il existe bien un index insensible à la casse pour  la clef d'une collection:
```
    private static void ensureCaseInsensitivity(MongoTemplate mongoTemplate, String collectionName) {
        MongoCollection<Document> collection = mongoTemplate.getCollection(collectionName);
        List<Document> indexes = StreamSupport.stream(collection.listIndexes().spliterator(), false).collect(Collectors.toList());
        Map<String, Document> indexPerName = indexes.stream().collect(Collectors.toMap(i -> (String)i.get("name"), Function.identity()));
        if (2 != (Integer) ((Document) indexPerName.get("_id_").get("collation")).get("strength")) {
            throw new RuntimeException("Collection ID is not case-insensitive");
        }
        if (2 != (Integer) ((Document) indexPerName.get("key_1").get("collation")).get("strength")) {
            throw new RuntimeException("Collection key is not case-insensitive");
        }
    }
```

**Comment by Lucas-C** [comment]
Comme je ne trouve pas le moyen de créer manuellement un collection au sein d'une appli SpringBoot avec `spring-data-mongodb`, une possibilité serait de **créer les collections avec leurs collations au démarrage du conteneur**. Voici ce que cela entrainerait :
- taguer les tests Cucumber vérifiant la sensibilité à la casse en `@integ-test-only` et les exclure lors de l'exécution des TUs BDD dans Travis CI (mais les exécuter via `tests/integration`)
- ajouter un client Mongo au `Dockerfile`
- ajouter un script shell d'entrypoint Docker qui créerait les collections, en se basant sur la variable d'environnement `$PROJECTION_REPOSITORY_MONGO_URI`
