### ISSUE TITLE
Diff des propriétés des modules implémenté dans le backend

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#381]
Demande du sondage 2017

**Comment by thomaslhostis** [comment]
- [ ] Étudier ce que font les outils standard de diff Json => définir le format de retour
- [ ] Proposition de premier use case à implémenter : diff sur les fichiers
- [ ] Autre proposition : diff de propriétés afin de pouvoir l'appeler via le front
- [ ] Commencer par l'ADR
- [ ] Tenter d'écrire les BDD en premier
