### ISSUE TITLE
Recherche de properties

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#384]
Demande émise lors du sondage 2017

En permettant de filtrer sur une appli ou une plateforme

\+ rajouter le champ de rechercher côté front

**Comment by Lucas-C** [comment]
Étude à faire sur usages actuels du batch de déversement dans Elasticsearch

**Comment by Lucas-C** [comment]
Demande rémonté ici également : https://github.com/voyages-sncf-technologies/hesperides/issues/443

**Comment by thomaslhostis** [comment]
Nous utilisons la version 3.4 de MongoDB. Bruno nous recommande de passer en 3.6 pour faciliter ce genre d'opérations de recherche.

Ne pas oublier de faire un dump avant : la version 3.6 nécessite une modification des données qui n'est pas rétrocompatible avec la version 3.4.

**Comment by Lucas-C** [comment]
Besoin à nouveau émis aujourd'hui côté Prodigy by Guy C.
Le besoin est de rechercher des propriétés par clef ou valeur, typiquement: `key:*url*` ou `value:*domain.com`

Notes:
- il faudra penser à empêcher la recherche de propriétés par valeur sur les mots de passe, si l'utilisateur n'a pas les droits de prod
-  il faudra être vigilant sur l'impact en termes de perfs de cette fonctionnalité

**Comment by Lucas-C** [comment]
Voici le LADR correspondant : https://github.com/voyages-sncf-technologies/hesperides/blob/master/documentation/lightweight-architecture-decision-records/search_properties.md

Cela a été implémenté & déployé, je clôture
