### ISSUE TITLE
Eviter les conflits en cas d'édition simultanée - PATCH /properties

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides#39]
To provide patch update asked here [#11](https://github.com/voyages-sncf-technologies/hesperides-gui/issues/11)

This new service will be like : 
```javascript
PATCH /{application_name}/platforms/{platform_name}/properties
{
   "key_value_properties":[
      {
         "name":"value6",
         "value":"value6"
      },
      {
         "name":"value2",
         "value":"value2"
      },
      {
         "name":"value5",
         "value":""
      }
   ],
   "iterable_properties":[

   ]
}
```
To illustrate the behaviour : 

**Before the patch**
value5 : old_value5
value2 : old_value3
value3 : old_value3

**After the patch**
value6 : value6
value2 : value2
value3 : old_value3

The **value6** property has been added with the requested value while the **value5** has been removed due of the empty string.

**Comment by Lucas-C** [comment]
Je viens de discuter un peu du contexte de cette demande avec Jordan :

> Si je suis sur la page et que je travail sur toto 
> mon appel back va me renvoyer un platform_vid 
> Si un mec va éditer un module plop 
> Il va m’invalider mon platform_vid, donc quand je vais save 
> Je vais me faire jeter 

Pour éviter ce scénario, sa suggestion est d'implémenter le verbe `PATCH` sur la ressource `/properties` avant de permettre la MAJ partielle de donnée.

La difficulté technique réside essentiellement dans la gestion du `.version_id`.
Voici plusieurs idées dans le cas du scénario d'édition simultanée de propriétés :

- les autres utilisateurs consultant cette même page reçoivent une MAJ d'Hesperides indiquant que ces propriétés ont été modifiées, et détectent si les modifs en cours sont en conflit

- la front effectue désormais une MAJ via `PATCH` et dans ce cas on ne tient pas seulement compte du `.version_id` pour autoriser les modifs de propriétés, mais également du properties_path : le backend accepte une modification des données avec un `.version_id` antérieur **si les modifs concernent un properties_path distinct** de celui des derniers changements

Enfin, cette fonctionnalité permettrait à terme de faire de l'_autosave_ dès qu'un utilisateur modifie un champ

**Comment by Lucas-C** [comment]
Une discussion aujourd'hui avec @Sylvain-maillard me fait envisager une alternative au `PATCH`: des appels à des sous-ressources. Exemples:
```
POST /applications/{application_name}/platforms/{platform_name}/modules
PUT /applications/{application_name}/platforms/{platform_name}/modules/1
```

**Comment by Lucas-C** [comment]
3e solution technique suggérée par Thomas pour le scénario d'édition simultanée de propriétés :
définir des versionIds pour les sous-niveaux d'entitées d'une plateforme -> modules déployés & instances
