### ISSUE TITLE
Comment traiter les 34 TODOs présents dans le code ?

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#392]
La liste exacte peut être obtenue ainsi :
```
$ grep -i 'todo[^m]' $(git ls-files)
```

Au-delà des avis personnels ( le mien étant que c'est [une mauvaise pratique](http://wiki.c2.com/?TodoCommentsConsideredHarmful) ), il faut qu'on décide comment gérer tous ces morceaux de code "à traiter plus tard".

Je suis d'avis de faire une passe pour vérifier qu'une _issue_ existe à chaque fois pour traiter le cas, et dans le cas contraire la créer.

**Comment by thomaslhostis** [comment]
Il n'y a plus de TODOs
