### ISSUE TITLE
When @pattern value is not escaped well, we get error

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides#44]
When hepserides @pattern value is not escaped well, we get error on file generation.

Ex : 
14:36:59	---> Downloading file logback-loggers-console.xml
14:36:59	Dangling meta character '*' near index 12
14:36:59	^"([a-z]{2}|*)-([A-Z]{2}|*)"(,"([a-z]{2}|*)-([A-Z]{2}|*)")*$

The idea is to make hesperides more Tolerant on that or validate patterns.

**Comment by Lucas-C** [comment]
A tester sur v4 si reproductible

**Comment by Lucas-C** [comment]
Testé avec la v4 : l'extraction fonctionne sans problème sans guillemets, avec cet input par exemple:
```
{{toto|@pattern _^"([a-z]{2}|_)-([A-Z]{2}|_)"(,"([a-z]{2}|_)-([A-Z]{2}|_)")_$}}
```

Par contre, afin d'être iso-legacy, on ne valide pas que le @pattern des templates sont sémantiquement valides.

Afin d'implémenter ça post-MEP, nous devrions :
- modifier `domain.templatecontainers.entities.Property` pour lever une erreur en cas de `@pattern` invalide tel que `{{toto|@pattern +}}`
- exécuter un test manuel d'intégration sur les données de prod : parcourir tous les `ModuleDocument` MongoDB, puis tester tous les `PropertyDocument.mustacheContent` pour voir si cette modification à un impact
- si l'impact est ok, à ajouter un test BDD et déployer cette validation

**Comment by Lucas-C** [comment]
La validation des `@pattern` sera traitée dans https://github.com/voyages-sncf-technologies/hesperides/issues/513
