### ISSUE TITLE
Possibilité de rechercher des propriétés ou des valeurs dans l'intégralité d'Hesperides

### ISSUE THREAD

**Issue by lenaing** [voyages-sncf-technologies/hesperides#443]
Il serait fort agréable de pouvoir effectuer une recherche d'une propriété ou d'une valeur dans l'intégralité des plateformes et des applications d'Hesperides.

Cas d'usage : migration de proxies, devoir trouver toutes les propriétés valorisées à `http://proxy-xxx/` ou contenant `proxy-xxx` ou contenant `proxy` par exemple :)

Nous avons déjà une solution "du pauvre" avec un export manuel vers ELS, mais avoir la fonctionnalité intégrée à l'outil serait un plus !

**Comment by Lucas-C** [comment]
En effet, c'est une demande identifiée :
https://github.com/voyages-sncf-technologies/hesperides/issues/384

Je clôture cette issue au profit de la précédente
