### ISSUE TITLE
Reindex on startup not working

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#45]
Hi,

reindex on startup not working cause, Aggregate start after reindexation.

In this case reindexation get empty list of modules, applications... 

Reset index in ELS not working.

Check if this behavior is fixed in new cache implementation #8.

**Comment by Lucas-C** [comment]
Sera géré dans https://github.com/voyages-sncf-technologies/hesperides/issues/377
