### ISSUE TITLE
GET /applications/

### ISSUE THREAD

**Issue by GurneyHallack** [voyages-sncf-technologies/hesperides#464]
**Is your feature request related to a problem? Please describe.**
I want to get all applications by a simple API query.

**Describe the solution you'd like**
A /GET/applications, with a possible paginations available if possible.
The result could be the same as GET /applications/{application_name} (platforms could be optional in this case, to reduce overload)

**Describe alternatives you've considered**
Using POST /applications/perform_search with each character of the alphabet, but it seems that there is a limit on the result returned.
Directly getting information from ElasticSearch (it requires a specific logic for it).

**Comment by Lucas-C** [comment]
Implémenté et en prod !

**Comment by thomaslhostis** [comment]
👍 (vu avec @GurneyHallack)
