### ISSUE TITLE
Remonter properties vides ou contenant des valeurs par défaut 

### ISSUE THREAD

**Issue by clegrand59** [voyages-sncf-technologies/hesperides#519]
Bonjour,
Avant de charger des properties hespérides via un JSON, j'aimerai le parser afin de vérifier que les properties du fichier existent vraiment dans hespérides.
Pour ca je lance un appel REST via l'API
Les properties vides ou par défaut ne remontant pas, mon test de cohérence échoue.
Serait-il possible de faire évoluer l'API pour que l'ensemble des properties remontent ?
Merci d'avance.
Cordialement,

    Christophe.

**Comment by thomaslhostis** [comment]
Il faut qu'on évalue les impacts que cela peut avoir sur le front notamment mais au pire on ajoutera un paramètre de requête.

**Comment by thomaslhostis** [comment]
Remarque de @JordanKergoat :

> Hello, 
C'est une mauvaise idée de faire ça, pour ma part je trouve le comportement parfaitement adapté. 
Les valorisation c'est une liste, le modèle (le template/les propriétés) en est une autre, donc non l'api n'a pas à faire cela. 
Le front (l'ihm) récupère la liste des propriétés et propose des les valorisé. Mais en effet il n'y a aucun controle sur les valorisation et c'est la que c'est bien. Pour des raisons d'historique, de changement de modèles.

**Comment by clegrand59** [comment]
Je ne demande pas à l'API de contrôler, c'est l'objet de mon script.
Par contre, si l'API ne retourne pas les propriétés vides (ou par défaut), il ne peut pas déterminer qu'il y a potentiellement un problème et on s'en apercevra lors du démarrage de l'instance, si elle plante.
Je voudrais faire planter le déploiement avant s'il y avait des ppties non valorisées.

**Comment by JordanKergoat** [comment]
Hello,
Dans ce cas, il te suffit de faire une requête sur l'endpoint model 

GET /modules/{module_name}/{module_version}/release/model
ou 
GET /modules/{module_name}/{module_version}/workingcopy/model

Avec ça, tu récupérera toutes les propriétés qui existent dans ton module hesperides, puis en faisant l'appel ci-après, tu pourra comparer s'il te manque des valorisations

GET /applications/{application_name}/platforms/{platform_name}/properties

A dispo

**Comment by clegrand59** [comment]
Ca pourrait coller avec ce que je veux faire. Je vais tenter ca, merci.

**Comment by Lucas-C** [comment]
@clegrand59 : as-tu toujours besoin de cette fonctionnalité ?

**Comment by clegrand59** [comment]
Non, c'est bon tu peux la fermer, je vais faire selon les précos de Jordan.
Merci !
