### ISSUE TITLE
Propriété avec valeur par défaut mais jamais valorisée non prise en compte

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#530]
Il arrive que les propriétés d'un module déployé ne soient jamais valorisées, cela ne doit pas empêcher de tenir compte des valeurs par défaut.

**Comment by thomaslhostis** [comment]
Il manque le test fonctionnel donc je rouvre.

**Comment by Lucas-C** [comment]
@thomaslhostis : ce n'est pas couvert par ce test ?
-> https://github.com/voyages-sncf-technologies/hesperides/blob/master/tests/bdd/src/test/resources/files/get-file.feature#L24

**Comment by thomaslhostis** [comment]
@Lucas-C La valorisation est vide mais il y a bien valorisation :)
