### ISSUE TITLE
Block null application insertion via API

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides#56]
User can insert a null value for application with the API.
It block get application service.

We should check null values for API rest services, and reject this request.

For example, a POST Request from_application&from_platform, but without application_name in the body

**Comment by Willymontaz** [comment]
We could both:
- check for "null" string value from the api
- also use Optional<...> as return types for all beans getters. This way we could compile check that we handle all possible Null cases

Example of such a bean

class Application {
  
   private String name;

   public Optional<String> getName() {
        return Optional.ofNullable(name);
   }
}

**Comment by bubulemaster** [comment]
In our case, in Platform class, field platform_name, application_name, application_version is not optionnal.

In other input object, check not null value in mandatory field and add optional on other field.

**Comment by mareths** [comment]
Thanks for your contribution :)
Add annotations NotNull and NotEmpty for platform_name, , application_name and application_version seems to do the job.

**Comment by bubulemaster** [comment]
Delivered !
