### ISSUE TITLE
[TECHNICAL] - Upgrade to DropWizard 1.0

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides#6]
Hesperides is still using dropwizard 0.7. Now dropwizard 1.0 is released.
We may upgrade to the dropwizard 1.0 release.

Dropwizard 1.0 brings new versions of all the used tools and frameworks like : jetty, jackon, Guava, AssertJ, Java8 capabilities, ...
You may want to take a look at : https://github.com/dropwizard/dropwizard/releases

Some useful links

https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-0.7.x-to-0.8.x
https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-0.8.x-to-0.9.x
https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-0.9.x-to-1.0.x

**Comment by victorsalaun** [comment]
Sur Hespérides v3, dropwizard est en version 1.2.2 sur master
