### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides#60]
When trying to edit a production platform without having production acces right. The displayed message is not the one expected. Instead you get :

"Saving is not possible. At least one property does not respect @required and/or @pattern annotations"

The correct message would be :

"Updating a production platform is reserved to production role"

**Comment by Lucas-C** [comment]
C'est un problème côté front : https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/src/app/i18n/label_en.json#L54

**Comment by Lucas-C** [comment]
Je ferme en faveur de https://github.com/voyages-sncf-technologies/hesperides-gui/issues/137
