### ISSUE TITLE
Update to jmustache

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides#62]
To make easier json template with iterable properties, an update to use jmustache instead of current version should be make.

Tipically usage is a better write of the json template, to add a comma after all element of the json, excepted the last, using the option '-index' and '-last' of jmustache

**Comment by Lucas-C** [comment]
Je ferme cette demande en faveur de https://github.com/voyages-sncf-technologies/hesperides/issues/375
