### ISSUE TITLE
Permettre le restaure de plateforme supprimée par erreur

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#622]
Il s'agit d'une demande d'un utilisateur

Il faudrait voir si l'historique d'évenements ne permet pas la reconstruction de la plateforme

**Comment by Lucas-C** [comment]
Si implémenté, on pourrait fournir un formulaire côté front pour accéder à cette fonctionnalité,
et en profiter pour ajouter un bouton de suppression de plateforme.

**Comment by thomaslhostis** [comment]
Je vois 2 solutions :
* Désactiver/réactiver la plateforme, à l'aide d'un flag, au lieu de la supprimer
* Supprimer le dernier évènement (`deleted`) directement dans l'EventStore et rejouer les évènements, mais c'est un peu sale

**Comment by Lucas-C** [comment]
J'ai opté pour la solution 2, qui je l'admets est peut-être plus "sale" mais moins impactante structurellement.

Je pars d'un principe qu'il s'agit d'une opération "de sauvetage" qui doit être tenté quasi immédiatement On ne pas garantit pas qu'elle fonctionnera après N heures/jours où un processus de nettoyage des events aura pu les supprimer.

Je viens de soumettre une PR.

**Comment by Lucas-C** [comment]
C'est implémenté côté API.
Je clôture cette issue et j'ai ouvert celle-ci côté front : https://github.com/voyages-sncf-technologies/hesperides-gui/issues/185
