### ISSUE TITLE
Donner accès à l'historique des modules déployés / changement de version d'une plateforme

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#627]
On pourrait ensuite faire évoluer le front pour l'afficher à l'utilisateur

**Comment by Lucas-C** [comment]
Chantier entamé par @mareths durant l'atelier de contribution de janvier 2020

**Comment by thomaslhostis** [comment]
Doublon de https://github.com/voyages-sncf-technologies/hesperides/issues/78
