### ISSUE TITLE
Allow to create a new working copy after module release

### ISSUE THREAD

**Issue by myrtion** [voyages-sncf-technologies/hesperides#63]
**As a** Java application developper using maven release process
**I want to** Follow my application's version flow during hesperides releases
**So that** I can easily automate my application release in a pipeline with hesperides 

Maven versioning example: 

- Initial version : 1.0-SNAPSHOT
- Release version : 1.0
- Next version 1.1-SNAPSHOT

To follow that versioning, a new working copy with the next version could be created after hesperides module release

**## Service update proposal**

Current service signature : 

/rest/modules/create_release?module_name=moduleName&module_version=1.0-SNAPSHOT&release_version=1.0

Service Signature after modification ( next_version query parameter is optional ) : 

/rest/modules/create_release?module_name=moduleName&module_version=1.0-SNAPSHOT&release_version=1.0&**next_version=1.1-SNAPSHOT**

**Comment by Lucas-C** [comment]
Salut @myrtion !

Il aura fallu du temps pour te répondre, désole.
Est-ce toujours un besoin pour toi ?
Je ne suis pas sûr qu'enrichir ainsi l'API [`POST create_release`](https://github.com/voyages-sncf-technologies/hesperides/blob/master/core/presentation/src/main/java/org/hesperides/core/presentation/controllers/ModulesController.java#L184) vaille le coup "simplement" pour éviter une 2e appel HTTP...
