### ISSUE TITLE
BDD: cas de MAJ de propriété avec le même nom mais 2 valeurs différentes dans la payload

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#648]
cf. https://github.com/voyages-sncf-technologies/hesperides/pull/647/files#diff-6

**Comment by Lucas-C** [comment]
Un exemple de payload de `PUT /applications/{application_name}/platforms/{platform_name}/properties` invalide :
```
[
  {
    "key": "foo",
    "value": 42
  },
  {
  {
    "key": "foo",
    "value": 0
  }
]
```

**Comment by thomaslhostis** [comment]
Créer un test fonctionnel qui essaie de sauvegarder une propriété déclarée 2 fois avec une valeur différente. L'appel doit renvoyer une erreur.
