### ISSUE TITLE
[Iterables property] when value is set and @comment is avaible, generate property is not set

### ISSUE THREAD

**Issue by aprodhomme** [voyages-sncf-technologies/hesperides#65]
Hi, 

I have added the @comment attribute on some of iterables properties. When only this attribute is used the value set is not inserted in the template when generating the files.

It works well when @required or @default is defined before @comment.

**Comment by Lucas-C** [comment]
A tester si reproductible dans v4

**Comment by Lucas-C** [comment]
Corrigé dans le refonte v4
Je clôs ce ticket
