### ISSUE TITLE
Global property usage in iterable properties

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides#66]
The feature that allow to find usage of global properties doesn't work if the global property is referenced in an iterable section.

**Comment by Lucas-C** [comment]
Il s'agit de la ressource `/applications/{application_name}/platforms/{platform_name}/global_properties_usage`.
Il faudrait commencer par vérifier si ce bug existe toujours depuis la refonte en ajoutant un test BDD

**Comment by thomaslhostis** [comment]
La fonctionnalité n'existait pas, c'est corrigé et testé :)
