### ISSUE TITLE
Une propriété itérable non valorisée ayant le même nom qu'une propriété simple valorisée ne prend pas sa valeur

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#660]
D'après Jordan, c'était le cas avant la refonte.

**Comment by Lucas-C** [comment]
Je ne vois pas de test couvrant ce cas dans nos BDDs pour le moment: https://github.com/voyages-sncf-technologies/hesperides/blob/master/tests/bdd/src/test/resources/files/get-file.feature

@JordanKergoat Est-ce qu'il y un réel besoin d'implémenter ce cas là ? Est-ce que ça a déjà provoqué des mauvaises surprises chez nos utilisateurs ?

**Comment by Lucas-C** [comment]
Confirmé par @JordanKergoat : ce problème n'apparait plus depuis la refonte
