### ISSUE TITLE
Impossible de récupérer l'historique des évènements d'un module dont le nom contient un underscore

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#665]
Erreur : Invalid stream name, expected format: module-$name-$version-$versionType or platform-$app-$platform

BIV > PRD1 > SQV

**Comment by Lucas-C** [comment]
Corrigé, c'était dû à un module en base dont le `key.name` était vide.

**Comment by Lucas-C** [comment]
J'ai supprimé ce module et j'ai vérifié qu'il est bien désormais impossible de créer un module avec comme nom une chaîne vide via l'API. Je clôture.
