### ISSUE TITLE
ACL : tester un user qui n'a pas de groupe

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#667]

**Comment by Lucas-C** [comment]
@thomaslhostis : tu envisageais plutôt un test BDD "simple" ou bien un test BDD d'intégration avec ` @require-real-ad` ?

**Comment by thomaslhostis** [comment]
Vu ensemble : le test n'a d'intérêt que si c'est un test d'intégration `@require-real-ad` :)
