### ISSUE TITLE
Remove sun packages

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#67]
In this Oracle's article: http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html

> In general, writing java programs that rely on sun.* is risky: those classes are not portable, and are not supported.

Here is the list of all sun packages we are using:
- com.sun.org.apache.xpath.internal.operations.Bool
- sun.reflect.generics.reflectiveObjects.NotImplementedException
- sun.misc.BASE64Decoder
- sun.reflect.generics.reflectiveObjects.NotImplementedException

**Comment by Lucas-C** [comment]
Nous n'utilisons plus aucun de ces 3 packages, je clôture
