### ISSUE TITLE
Masquer les mots de passes pour la resource /applications/platforms

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#684]
Cette ressource créée récemment (cf. https://github.com/voyages-sncf-technologies/hesperides/issues/675) ne suit pas les même restrictions de confidentialité que les autres endpoints :
- https://github.com/voyages-sncf-technologies/hesperides/blob/master/core/application/src/main/java/org/hesperides/core/application/platforms/PlatformUseCases.java#L180
- https://github.com/voyages-sncf-technologies/hesperides/blob/master/core/application/src/main/java/org/hesperides/core/application/files/FileUseCases.java#L169

**Comment by thomaslhostis** [comment]
Le json retourné ne contient pas les propriétés valorisées au niveau du module, seulement les propriétés globales et les propriétés d'instances qui ne peuvent pas être taggées "@password".

**Comment by thomaslhostis** [comment]
Vu avec l'équipe Prodigy : nous attendons de savoir s'ils souhaitent récupérer les propriétés valorisées au niveau des modules dans ce endpoint. Si c'est le cas, il faudra cacher les mots de passe.

**Comment by Lucas-C** [comment]
Difficile à débuguer sans les sourcemaps de swagger-ui: https://github.com/springfox/springfox/issues/3114

**Comment by Lucas-C** [comment]
C'est ok, je clôture
