### ISSUE TITLE
/applications/using_module renvoie des plateformes qui n'utilisent plus le module en question

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#685]
Il semble que la requête renvoie les plateformes ayant utilisé le module fourni en paramètre, donc archivé, et _sans tenir compte de la version ou du type de version_.

**Comment by Lucas-C** [comment]
J'ai commencé à travailler sur une PR dans #688 mais je n'ai pas encore réussi à reproduire ce cas
