### ISSUE TITLE
Rewrite Unit Test

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#69]
Actually, many units tests use mock.

But with time, we see many tests return OK but in reality, they are false (e.g. return an exception that never raise).

Whith `JedisMock class`, we can made unit test/integration test locally (maybe a new sort of tests :wink:)

We need remove maximum of mock.

`As always, should you or any of your I.M. Force be caught or killed, the Secretary will disavow any knowledge of your actions. This tape/disc will self-destruct in five/ten seconds. Good luck, Dan/Jim.`

**Comment by Lucas-C** [comment]
Géré au sein de la refonte
