### ISSUE TITLE
Delete spaces after key name in templates

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides#7]
If I create the following property :

```
foo={{foo |default 10}}
```

then key name is "foo " (with space) and it can be misleading. Hesperides should delete directly the space

**Comment by nboury-vsct** [comment]
actually the pull request did not work for properties which were already saved with an empty space (before or after key name)

**Comment by stidiovip** [comment]
This sould take care alredy existing values and new values.

**Comment by stidiovip** [comment]
This issue is now fixed and merged with the master

**Comment by stidiovip** [comment]
Fixed on release 2.0.0
