### ISSUE TITLE
Could Hesperides allow CORS ?

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#70]
In concrete termes, could every call to the API return the HTTP header:
```
Access-Control-Allow-Origin: *
```

**Comment by victorsalaun** [comment]
Do you have any specific use case in mind?

**Comment by Lucas-C** [comment]
Yes: I want to build a back-office web interface that would display the current version in Hesperides, and some properties values

**Comment by victorsalaun** [comment]
Best practices on how to CORS:
- dev: you allow all origins
- prod: specify origins

In your case it's for dev. I suggest a dev profile enabling all origins. What do you think?

**Comment by Lucas-C** [comment]
Why not, but I would like this applied on voyages-sncf-technologies internal instance.
So I think it may be better instead to make a distinction between:
- public: Internet-facing instance, explicit CORS rules per partner hostnames
- internal: relaxed-wildcard CORS rule

What do you think ?

**Comment by victorsalaun** [comment]
As the back end is protected with basic auth for every request, I think you can go with your proposal.

**Comment by Lucas-C** [comment]
N'ayant plus ce besoin, je clôs cette _issue_
