### ISSUE TITLE
Utiliser une List dans IterablePropertyItemIO pour être cohérent avec les couches domaine & infrastructure

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides#705]
- [IterablePropertyItemIO.java](https://github.com/voyages-sncf-technologies/hesperides/blob/master/core/presentation/src/main/java/org/hesperides/core/presentation/io/platforms/properties/IterablePropertyItemIO.java)
- [IterablePropertyItem.java](https://github.com/voyages-sncf-technologies/hesperides/blob/master/core/domain/src/main/java/org/hesperides/core/domain/platforms/entities/properties/IterablePropertyItem.java)
- [IterablePropertyItemView.java](https://github.com/voyages-sncf-technologies/hesperides/blob/master/core/domain/src/main/java/org/hesperides/core/domain/platforms/queries/views/properties/IterablePropertyItemView.java)
- [IterablePropertyItemDocument.java](https://github.com/voyages-sncf-technologies/hesperides/blob/master/core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/platforms/documents/IterablePropertyItemDocument.java)

En s'assurant qu'on interdit bien le cas des 2 propriétés avec le même nom en input du `PUT / /properties`

Point bloquant pour le moment : ce changement casse certains tests BDD

**Comment by pepcitron** [comment]
Voici les tests BDD impactés par le changement :

Failed scenarios:
modules/create-modules.feature:19 # Scenario: forbid creation of a module with a same name but different letter case
modules/get-modules.feature:19 # Scenario: get the detail of an existing module with the wrong letter case
modules/get-modules.feature:25 # Scenario: get the detail of a module whose name contains a slash and a percent sign
platforms/create-platforms.feature:30 # Scenario: forbid creation of a platform with a same name but different letter case
platforms/get-platforms.feature:13 # Scenario: get the detail of an existing platform with the wrong letter case
platforms/get-properties-diffs.feature:6 # Scenario: get properties diffs between two platforms with valued properties
technos/create-technos.feature:18 # Scenario: forbid creation of a techno with a same name but different letter case
technos/get-technos.feature:12 # Scenario: get the detail of an existing techno with the wrong letter case

320 Scenarios (8 failed, 312 passed)
1610 Steps (8 failed, 6 skipped, 1596 passed)
3m41.737s

**Comment by Lucas-C** [comment]
En lien : https://github.com/voyages-sncf-technologies/hesperides/issues/648

**Comment by Lucas-C** [comment]
La correction de @pepcitron est contenu dans cette PR : https://github.com/voyages-sncf-technologies/hesperides/pull/703
