### ISSUE TITLE
Docker automatic build

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#71]
Using Travis CI, a docker image can be automatically build at the end of the build.
The tag latest should be for any build (e. g. latest dev build).
When releasing hesperides, a tag named be its version should be made.

At the moment there is one docker image tagged latest and its not up to date.

Two images can be created, one for hesperides and the other for hesperides-gui.
One top of them a third image can be build containing the front and the back of hesperides convenient for demos.

**Comment by Lucas-C** [comment]
Done, apart from the combined image, but launching both can easily be done with a Docker compose/swarm YAMl file: https://github.com/voyages-sncf-technologies/hesperides/blob/master/docker/docker-compose.yml
