### ISSUE TITLE
Prévenir l'utilisation de working copy en production

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides#719]
Hello,
Il serait intéressant de connaitre (voir d'empêcher) l'ajout de version de module en working copy pour toute plateforme tagé ou se nommant PRD.

**Comment by Lucas-C** [comment]
Tu l'as déjà créé ce ticket ^^
-> https://github.com/voyages-sncf-technologies/hesperides/issues/47
