### ISSUE TITLE
Rework module searchOne api path service

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#72]
Actually,

when you search one module (use by GUI in `properties.js` in function  `check_modules_models(modules)`), you call rest API `/rest/modules/search` with querystring `terms` equals to `<modulename> <moduleversion> true/false`.

It's not really clear and if you call with missing term, you've got: 
```
{
  "status": 500,
  "exception": "java.lang.ArrayIndexOutOfBoundsException",
  "message": null,
  "stacktrace": "java.lang.ArrayIndexOutOfBoundsException\n"
}
```

Because all terms is requiered, API must be `/rest/modules/search/one/{module_name}/{module_version}/{module_type}`

**Comment by Lucas-C** [comment]
We will tackle this problem with unclear error messages in https://github.com/voyages-sncf-technologies/hesperides/issues/357
