### ISSUE TITLE
Rework template package searchPackages api path service

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#73]
Actually,

when you search template package (use by GUI in `techno.js` in function  `with_name_like(name)`), you call rest API `/rest/templates/packages/perform_search` with querystring `terms` equals to `<template_name>#<template_version>`.

It's not really clear and if you call with missing term, you've got: 
```
{
  "status": 400,
  "exception": "java.lang.IllegalArgumentException",
  "message": "Query parameter terms is missing",
  "stacktrace": "java.lang.IllegalArgumentException: Query parameter terms is missing
```

Because first terms is requiered, API must be `/rest/templates/packages/search/{template_name}?version={optional_version}`

NOTE : we change `/templates/packages/perform_search` to `/templates/packages/search`, it's more clear.

**Comment by Lucas-C** [comment]
We will tackle this problem with unclear error messages in https://github.com/voyages-sncf-technologies/hesperides/issues/357
