### ISSUE TITLE
Rework module searchPackages api path service

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#74]
Actually,

when you search module (use by GUI in `module.js` in function  `with_name_like(name)`), you call rest API `/rest/modules/perform_search` with querystring `terms` equals to `<module_name><module_version>`.

It's not really clear and if you call with missing term, you've got: 
```
{
  "status": 400,
  "exception": "java.lang.IllegalArgumentException",
  "message": "Query parameter terms is missing",
  "stacktrace": "java.lang.IllegalArgumentException: Query parameter terms is missing
```

Because first terms is requiered, API must be `/rest/modules/search/{module_name}?version={optional_version}`

NOTE : we change `/modules/perform_search` to `/modules/search`, it's more clear.

**Comment by Lucas-C** [comment]
We will tackle this problem with unclear error messages in https://github.com/voyages-sncf-technologies/hesperides/issues/357
