### ISSUE TITLE
Rework module searchApplications api path service

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#75]
Actually,

when you search application (use by GUI in `application.js` in function  `with_name_like(name)`), you call rest API `/rest/applications/perform_search` with querystring `terms` equals to `<application_name>`.

It's not really clear and if you call with missing term, you've got: 
```
{
  "status": 400,
  "exception": "java.lang.IllegalArgumentException",
  "message": "Query parameter terms is missing",
  "stacktrace": "java.lang.IllegalArgumentException: Query parameter terms is missing
```

Because first terms is requiered, API must be `/rest/applications/search/{application_name}`

NOTE : we change `/applications/perform_search` to `/applications/search`, it's more clear.

**Comment by Lucas-C** [comment]
We will tackle this problem with unclear error messages in https://github.com/voyages-sncf-technologies/hesperides/issues/357
