### ISSUE TITLE
Rework module searchPlatforms api path service

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#76]
Actually,

when you search application (use by GUI in `application.js` in function  `get_platform_name_of_application(application_name, platform_name)`), you call rest API `/rest/applications/platforms/perform_search=` with querystring `applicationName` equals to `<application_name>` and `platformName`. equals to `<plateform_name>`

It's not really clear and if you call with missing term, you've got: 
```
{
  "status": 400,
  "exception": "java.lang.IllegalArgumentException",
  "message": "Query parameter terms is missing",
  "stacktrace": "java.lang.IllegalArgumentException: Query parameter terms is missing
```

Because first terms is requiered, API must be `/rest/applications/search/{application_name}/platforms` that return all platform of application.

To specify platform name you have choice between querystring `platformName`. equals to `<plateform_name>` or new api path `/rest/applications/search/{application_name}/platform/{plateform_name}`.

I think second is best an more clear. Becarefull, I've remove **s** to platform word.

NOTE : we change `/applications/platforms/perform_search` to `/applications/search/<>/platfoms`, it's more clear.

**Comment by Lucas-C** [comment]
We will tackle this problem with unclear error messages in https://github.com/voyages-sncf-technologies/hesperides/issues/357
