### ISSUE TITLE
Eviter la création de doublons à la réception d'une requête dupliquée

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#779]
Un module a été créé en double par un appel effectué 2 fois "au même moment", ce qui rend la lecture de ce module impossible et crée une corruption de données.

Une solution serait de ne plus utiliser d'UUID comme identifiant d'agrégat mais un hash de la clé fonctionnelle pour qu'Axon rejette automatiquement la réception de 2ème commande.

**Comment by Lucas-C** [comment]
Je pense que ça permettrait de lever une exception ici: https://github.com/AxonFramework/AxonFramework/blob/axon-4.2/modelling/src/main/java/org/axonframework/modelling/command/AbstractRepository.java#L96

Dans tous les cas, la difficulté résidera à répliquer le cas d'erreur...

**Comment by Lucas-C** [comment]
Note: penser à ajouter un LADR pour expliquer ce choix
