### ISSUE TITLE
Améliorer la description des actions faites dans l'historique des évènements d'une plateforme

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides#78]
When I change module version or create new instance or another action which not required explicit comments, the history show generic message "<user> has updated the platform"

For each commit in db due to REST call api which not included comment, we should generate an automatic comment message with information of the action

**Comment by Lucas-C** [comment]
Salut @mareths !
Pour bien comprendre, tu souhaiterais que le message "has updated the platform" soit remplacé par qqch de plus explicite / détaillé, c'est ça ?

**Comment by mareths** [comment]
Yep, je pensais par exemple lors d'un montée de version à un message du type "machin has updated the plateform from <version n> to <version n+1>
Quand on regarde l'historique d'une application, on a généralement une grosse majorité de message avec juste "machin has updated the platform" qui n'indique pas grand chose en fait sur les différents changement de version de module de l'application.

**Comment by Lucas-C** [comment]
Oui, ça recoupe une demande du sondage
Merci pour les précisions !

**Comment by Lucas-C** [comment]
> même pour rundeck_user

**Comment by Lucas-C** [comment]
En lien :
- https://github.com/voyages-sncf-technologies/hesperides/issues/696 (Ajout ressource /events/applications/$app)
- https://github.com/voyages-sncf-technologies/hesperides-gui/issues/283 (Réintroduire les commentaires et la possibilité de faire des diffs dans l'historique des événements)
- https://github.com/voyages-sncf-technologies/hesperides/issues/303 ( Historiques des évenements Modules/Technos)

**Comment by thomaslhostis** [comment]
LADR : https://github.com/voyages-sncf-technologies/hesperides/blob/master/documentation/lightweight-architecture-decision-records/events/platform_events.md
