### ISSUE TITLE
Fournir la liste des propriétés d'une plateforme avec : valeur par défaut, valeur saisie et valeur finale

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#782]
L'équipe PAO a exprimé le besoin de récupérer la liste complète des propriétés d'une plateforme avec, comme pour le diff, l'affichage des valeurs stockées et des valeurs finales, et le cas échéant la valeur par défaut et la valeur de propriété globale qu'elles référencent.

L'idée est de les aider à nettoyer leurs propriétés qui semblent devenir compliquées à maintenir à cause du volume de données.

**Comment by Lucas-C** [comment]
Je suggère une évol sur `GET /properties` : ajouter un _query param_ `detailed=true` permettant d'inclure le même output que `GET /properties/diff`:
```
{
  ...
  "values": [
    {
      "name": ...,
      "value": ...,
      "finalValue": ...,
      "defaultValue": ...,
      "transformations": [...]
    }
  ]
}
```

A traiter en même temps que https://github.com/voyages-sncf-technologies/hesperides/issues/402 ?

**Comment by thomaslhostis** [comment]
Pour l'instant on ne préoccupe pas des propriétés itérables

**Comment by thomaslhostis** [comment]
Lié à https://github.com/voyages-sncf-technologies/hesperides-gui/issues/345
