### ISSUE TITLE
Get properties with the given path in a platform dont' return global value

### ISSUE THREAD

**Issue by tmonteyne** [voyages-sncf-technologies/hesperides#80]
The rest service "get /applications/{application_name}/platforms/{platform_name}/properties"  don't return global value like IHM.

**Comment by victorsalaun** [comment]
To get global properties use "get /applications/{application_name}/platforms/{platform_name}/properties?path=#"
Does it work for you?

**Comment by bubulemaster** [comment]
The issue is: no service avaible to get final proporties like populate in file.

**Comment by bubulemaster** [comment]
The dev is done but I think is not release in next version.

Many change has been need to do this and it's maybe cause regression.
