### ISSUE TITLE
Permettre le nettoyage des propriétés inutilisées

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides#803]
Cette fonctionnalité est présente dans le frontend. L'idée est de la rapatrier dans le backend et de proposer le nettoyage au niveau module mais aussi au niveau de la plateforme.

La rendre disponible dans l'API permettrait de l'inclure à la sharedLib => https://github.com/voyages-sncf-technologies/hesperides-jenkins-lib/issues/36

Issue front pour le nettoyage au niveau de la plateforme : https://github.com/voyages-sncf-technologies/hesperides-gui/issues/316

**Comment by Lucas-C** [comment]
LADR à prévoir pour définir la nouvelle ressource REST

**Comment by thomaslhostis** [comment]
ADR : https://github.com/voyages-sncf-technologies/hesperides/blob/issue_803/documentation/lightweight-architecture-decision-records/clean_unused_properties.md

**Comment by thomaslhostis** [comment]
Vérifier que les propriétés suivantes ne sont pas supprimées :

* Propriétés présentes dans les templates des technos
* Propriétés absentes du modèle mais référencées par d'autres propriétés
