### ISSUE TITLE
Add JenkinsFile

### ISSUE THREAD

**Issue by victorsalaun** [voyages-sncf-technologies/hesperides#84]
We should add some JenkinsFiles, at least two:
* one for ordinary build launched after every push
* one for nightly build (check test, sonar...)

Features:
* The ability to version control our job configuration
* Nice UI for visualizing build stages
* Easy monitoring and statistics collection on average stage timing
* Faster debugging of build failure

Reference: http://keyanp.com/what-to-expect-when-youre-expectingto-write-a-jenkinsfile.html

**Comment by Lucas-C** [comment]
Fait
