### ISSUE TITLE
Iterable properties miscount

### ISSUE THREAD

**Issue by MaximeAnsquer** [voyages-sncf-technologies/hesperides#88]
- I had 2 iterable properties defined in my mustache template 
- I changed the name of one of them (#NAME became #NEW_NAME in the template)
- The platform page now displays " Iterable properties (3) " whereas I only have two iterable properties

**Comment by JordanKergoat** [comment]
Hello,

This is not an issue, you do have two iterables properties, but you also have a record of your "deleted" iterable property.

If I'm not mistaken you should be able to verify my sayings by switching on the toogle to be able to see deleted properties.

**Comment by Lucas-C** [comment]
No feedback from initial requester for one year, closing this
