### ISSUE TITLE
Abstract store layer

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides#9]
Actually, Hesperides can only work with Redis.

The goal is to provide an abstract layer to allow create new connector in jar for MongoDB, Cassandra, PostegreSQL (https://vimeo.com/131740618), RethinkDB...

Do same for search to provide abstract layer to store Hesperides index.

New cache implementation is required before do this.

In good case why a project migrate form RethinkDB and ELS to PostgreSQL : https://medium.com/fuzzy-sharp/migrating-to-postgres-2dc1519a6dc7

**Comment by Lucas-C** [comment]
Implémenté lors de la refonte, je ferme cette _issue_
